version: 2
jobs:
  android:
    working_directory: ~/weipay
    docker:
        - image: circleci/android:api-28-node8-alpha

    steps:
      - checkout:
          path: ~/weipay
      - attach_workspace:
          at: ~/weipay

      - run:
          name: Install NPM packages
          command: npm i
      - run: sh .circleci/download.sh
      - run: mkdir -p ~/.gradle && mv gradle.properties ~/.gradle && mv wei-pay-android.keystore ./android/app
      - run: gem install fastlane -N --silent
      - run: fastlane android beta

      - persist_to_workspace:
          root: ~/weipay
          paths:
            - node_modules

workflows:
  version: 2
  react-native:
    jobs:
      - android:
          filters:
            branches:
              only:
                - staging