version: 2
jobs:
  android:
    working_directory: ~/weipay-android
    # environment:
    #     GRADLE_PROPERTIES_URL: https://www.dropbox.com/s/2bt0u7ox1763o02/gradle.properties?dl=0
    #     KEYSTORE_DOWNLOAD_URL: https://www.dropbox.com/s/73e3l3h47xzbmkl/wei-pay-android.keystore?dl=0

    docker:
      - image: circleci/android:api-28-node8-alpha

    steps:
      - checkout:
          path: ~/weipay-android
      - attach_workspace:
          at: ~/weipay-android
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.4" > ~/.ruby-version
      - run: sh .circleci/download.sh
      - run: mkdir -p ~/.gradle && cp gradle.properties ~/.gradle && cp wei-pay-android.keystore ./android/app
      - run: gem install fastlane -NV
      - run: fastlane android alpha
      - persist_to_workspace:
          root: ~/weipay-android
          paths:
            - node_modules